[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "yynb"
author = "YY"
author-email = "2907047490@qq.com"
classifiers = ["License :: OSI Approved :: MIT License"]

