[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "yynb"
author = "Caiji"
author-email = "i@qcmiao.cn"
classifiers = ["License :: OSI Approved :: MIT License"]

